%plot_function(density,'$\bar{n}$',tf,false,[0,1])
%plot_function(-u_e,'$|\bar{u}_e|$',tf,false,[0,1])
%plot_function(u_ion,'$\bar{u}_i$',tf,false,[0,1])
plot_function(E_field,'$\bar{E}$',tf,false,[-0.5,1.2])
%plot_function(E_T,'$\bar{E}$',tf,false,[-0.5,1.2])
plot_function(E_B,'$\bar{E}$',tf,false,[-0.5,1.2])
plot_function(Er,'$\bar{E}$',tf,true,[-10,40])
%plot_function(A,'$\bar{A}$',tf,false,[0,1])